# Generated by Django 6.0.7 on 2026-08-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_total_price_with_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan'), ('PENDING', 'Tasdiqlanishi kutilmoqda'), ('CANCELLED', 'Bekor qilindi'), ('DELIVERED', 'Yetkazildi')], default='PENDING', max_length=20),
        ),
    ]
