# Generated by Django 6.0.7 on 2026-08-10 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitemcontribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitemcontribution',
            constraint=models.UniqueConstraint(fields=('created_by', 'order_item'), name='unique_item_owner'),
        ),
    ]
