# Generated by Django 6.0.7 on 2026-08-10 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitemcontribution_unique_item_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPriceByUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=3, default=0.0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='orderitemcontribution',
            name='unique_item_owner',
        ),
        migrations.AddField(
            model_name='orderpricebyuser',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderpricebyuser',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='orders.order'),
        ),
        migrations.RemoveField(
            model_name='orderitemcontribution',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orderitemcontribution',
            name='order_item',
        ),
        migrations.AddConstraint(
            model_name='orderpricebyuser',
            constraint=models.UniqueConstraint(fields=('order', 'changed_by'), name='unique_employee_per_department'),
        ),
        migrations.DeleteModel(
            name='OrderItemContribution',
        ),
    ]
