# Generated by Django 6.0.7 on 2026-08-10 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderpricebyuser_and_more'),
        ('products', '0002_alter_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderpricebyuser',
            name='unique_employee_per_department',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product', 'ordered_by'), name='unique_order_product_contributor'),
        ),
        migrations.DeleteModel(
            name='OrderPriceByUser',
        ),
    ]
