# Generated by Django 6.0.7 on 2026-08-10 13:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_orderpricebyuser_unique_employee_per_department_and_more'),
        ('products', '0002_alter_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemConribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_order_product_contributor',
        ),
        migrations.AddField(
            model_name='orderitemconribution',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_contribution', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitemconribution',
            name='ordered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitemconribution',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items_contribution', to='products.product'),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered_by',
        ),
        migrations.AddConstraint(
            model_name='orderitemconribution',
            constraint=models.UniqueConstraint(fields=('order', 'product', 'ordered_by'), name='unique_order_product_contributor'),
        ),
    ]
