# Generated by Django 6.0.7 on 2026-08-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitemconribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemconribution',
            name='peak_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitemconribution',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
