# Generated by Django 6.0.7 on 2026-08-05 10:16

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('image', models.ImageField(blank=True, null=True, upload_to='market_images/')),
                ('description', models.TextField(blank=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('WAITING', 'Buyurtmani kutmoqda'), ('AVAILABLE', 'Mahsulotlar mavjud'), ('POSSIBLE', "Mahsulot kerak bo'lishi mumkin"), ('NO_CONNECTION', "Do'kon bilan aloqa uzildi"), ('NOT_NEEDED', 'Hozircha buyurtma kerak emas')], default='NOT_NEEDED', max_length=50)),
                ('color_code', models.CharField(choices=[('WAITING', '#0084FF'), ('AVAILABLE', '#2AB300'), ('POSSIBLE', '#FFB52F'), ('NO_CONNECTION', '#FF00B3'), ('NOT_NEEDED', '#FF2F2F')], default='WAITING', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
