# Generated by Django 6.0.7 on 2026-08-05 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketstatus',
            name='last_order_given_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_order_given_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketstatus',
            name='last_order_taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_order_taken_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketstatus',
            name='market',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='markets.market'),
        ),
    ]
