# Generated by Django 6.0.7 on 2026-08-05 14:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_market_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
