# Generated by Django 6.0.7 on 2026-08-07 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_alter_market_owner'),
        ('orders', '0004_order_approved_at_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketstatus',
            name='last_order_given_by',
        ),
        migrations.RemoveField(
            model_name='marketstatus',
            name='last_order_taken_by',
        ),
        migrations.AddField(
            model_name='marketstatus',
            name='last_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_status', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='marketstatus',
            name='color_code',
            field=models.CharField(choices=[('WAITING', '#0084FF'), ('AVAILABLE', '#2AB300'), ('POSSIBLE', '#FFB52F'), ('NOT_NEEDED', '#FF2F2F')], default='WAITING', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketstatus',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Buyurtmani kutmoqda'), ('AVAILABLE', 'Mahsulotlar mavjud'), ('POSSIBLE', "Mahsulot kerak bo'lishi mumkin"), ('NOT_NEEDED', 'Hozircha buyurtma kerak emas')], default='NOT_NEEDED', max_length=50),
        ),
    ]
