# Generated by Django 6.0.7 on 2026-08-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_remove_marketstatus_last_order_given_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketstatus',
            name='color_code',
            field=models.CharField(choices=[('PENDING', '#A855F7'), ('WAITING', '#3B82F6'), ('AVAILABLE', '#22C55E'), ('POSSIBLE', '#F59E0B'), ('NOT_NEEDED', '#EF4444')], default='WAITING', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketstatus',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Buyurtmani kutmoqda'), ('AVAILABLE', 'Mahsulotlar mavjud'), ('POSSIBLE', "Mahsulot kerak bo'lishi mumkin"), ('NOT_NEEDED', 'Hozircha buyurtma kerak emas'), ('PENDING', 'Buyurtma tasdiqlanishi kutilmoqda')], default='NOT_NEEDED', max_length=50),
        ),
    ]
