# Generated by Django 6.0.7 on 2026-08-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0007_alter_marketstatus_color_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='credit_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
