# Generated by Django 6.0.7 on 2026-08-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='customer',
            new_name='market',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
