# Generated by Django 6.0.7 on 2026-08-11 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0008_market_credit_amount'),
        ('orders', '0010_orderitemconribution_peak_quantity_and_more'),
        ('transactions', '0003_rename_customer_payment_market_alter_payment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='amount_must_be_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__gt', 0)), name='allocated_amount_must_be_greater_than_zero'),
        ),
    ]
