# Generated by Django 6.0.7 on 2026-08-11 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_payment_amount_must_be_greater_than_zero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='transactions.payment'),
        ),
    ]
